stages:
        - deploy

mirror:
        stage: deploy
        only:
                - tags
                - master
        script:
                - 'git status ; for url in $MIRROR_GIT_URLS ; do echo ; echo "$url" ; git push -f "$url" --tags origin/master:refs/head/master; done'

